/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Font;
import java.awt.GridLayout;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.UniCareerAdvisor;
import model.UniCareerAdvisorDir;
import model.UniCollege;
import model.UniCollegeDir;
import model.UniDepartment;
import model.UniDepartmentDir;
import model.UniExamCell;
import model.UniExamCellDir;
import model.UniStudent;
import model.UniStudentDir;
import model.University;
import model.UniversityDir;

/**
 *
 * @author naini
 */
public class SystemAdminUniversityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Uni_ExamCell_JPanel
     */
    JSplitPane splitPane;
    UniStudent selectedStudent = new UniStudent();
    UniCollegeDir uniColleges = new UniCollegeDir();
    UniversityDir universities = new UniversityDir();
    UniDepartmentDir uniDepartments = new UniDepartmentDir();
    UniStudentDir uniStudents = new UniStudentDir();
    UniExamCell selectedUniExamCell = new UniExamCell();
    Integer selectedUniversityId = 0;
    Integer selectedCollegeId = 0;
    Integer selectedDepartmentId = 0;
    Integer selectedRow = -1;
    University selectedUni = new University();
    
    UniCareerAdvisorDir advisors = new UniCareerAdvisorDir();
    UniExamCellDir examCell = new UniExamCellDir();
    
    Connection conn = null;
    
    public SystemAdminUniversityJPanel(JSplitPane splitPane, Connection conn) {
        initComponents();
        
        this.splitPane = splitPane;
        this.conn = conn;
        
        tblUniversity.getTableHeader().setFont( new Font( "Trebuchet MS" , Font.PLAIN, 18 ));
//        this.selectedUniExamCell = selectedUniExamCell;
        lblHeading2.setText(this.selectedUniExamCell.getName());
        getAllUniversityData();
        
        selectedCollegeId = 1;
        getAllStudents();
        getAllExamCells();
        getAllAdvisors();
        clearAllFields();
        populateCompaniesTable(universities);
//        populateStudentTable(uniStudents);

        btnAdvisor.setEnabled(false);
        btnExamCell.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUniversity = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnAdd = new button.Button();
        btnDelete = new button.Button();
        btnSearch = new button.Button();
        btnRefreshTable = new button.Button();
        btnClear = new button.Button();
        btnViewSelected = new button.Button();
        txtUniversityName = new javax.swing.JTextField();
        txtPasswordExam = new javax.swing.JTextField();
        btnLogOut = new button.Button();
        lblStudentName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtUsernameExam = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblHeading2 = new javax.swing.JLabel();
        lblHeading1 = new javax.swing.JLabel();
        txtAdvisorName = new javax.swing.JTextField();
        txtExamCellName = new javax.swing.JTextField();
        txtDepartmentName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblStudentName1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUsernameAdvisor = new javax.swing.JTextField();
        txtPasswordAdvisor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnExamCell = new javax.swing.JButton();
        btnAdvisor = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 650));

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 102));
        kGradientPanel1.setkGradientFocus(600);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 51, 51));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1005, 700));

        tblUniversity.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        tblUniversity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "University Id", "University Name", "Career Advisor", "Exam Cell Manager"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUniversity);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Password");

        btnAdd.setBackground(new java.awt.Color(204, 255, 204));
        btnAdd.setForeground(new java.awt.Color(0, 0, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_5.png"))); // NOI18N
        btnAdd.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 255, 204));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_6.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(204, 255, 204));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_7.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRefreshTable.setBackground(new java.awt.Color(204, 255, 204));
        btnRefreshTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_4.png"))); // NOI18N
        btnRefreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTableActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(204, 255, 204));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_8.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnViewSelected.setBackground(new java.awt.Color(204, 255, 204));
        btnViewSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_9.png"))); // NOI18N
        btnViewSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSelectedActionPerformed(evt);
            }
        });

        txtUniversityName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        txtPasswordExam.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        btnLogOut.setBackground(new java.awt.Color(204, 204, 255));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_3.png"))); // NOI18N
        btnLogOut.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblStudentName.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentName.setText("University Name");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Username");

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("UNIVERSITY DETAILS");

        txtUsernameExam.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtUsernameExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameExamActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblHeading2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N

        lblHeading1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N

        txtAdvisorName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtAdvisorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdvisorNameActionPerformed(evt);
            }
        });

        txtExamCellName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        txtDepartmentName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtDepartmentName.setEnabled(false);
        txtDepartmentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartmentNameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Department Names");

        lblStudentName1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblStudentName1.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentName1.setText("Exam Cell Name");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Advisor Name");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Username");

        txtUsernameAdvisor.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtUsernameAdvisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameAdvisorActionPerformed(evt);
            }
        });

        txtPasswordAdvisor.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Password");

        btnExamCell.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnExamCell.setText("<html>Login As <br>Exam Cell</html>");
        btnExamCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamCellActionPerformed(evt);
            }
        });

        btnAdvisor.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnAdvisor.setText("<html>Login As <br>Exam Cell</html>");
        btnAdvisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvisorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefreshTable, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnViewSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(lblHeading1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblHeading2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(237, 237, 237)
                                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtPasswordAdvisor, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                        .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtUniversityName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                        .addComponent(lblStudentName1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtExamCellName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtAdvisorName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(87, 87, 87)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtUsernameExam, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtPasswordExam, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtUsernameAdvisor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnExamCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAdvisor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addGap(138, 138, 138))))
        );

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnClear, btnDelete, btnRefreshTable, btnSearch, btnViewSelected});

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPasswordExam, txtUniversityName});

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSave, btnUpdate});

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPasswordAdvisor, txtUsernameAdvisor});

        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(lblHeading2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addComponent(lblHeading1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefreshTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnViewSelected, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblStudentName)
                        .addComponent(txtUniversityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentName1)
                            .addComponent(txtExamCellName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsernameExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPasswordExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnExamCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUsernameAdvisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtPasswordAdvisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAdvisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdvisorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, btnClear, btnDelete, btnRefreshTable, btnSearch, btnViewSelected});

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtPasswordExam, txtUniversityName});

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSave, btnUpdate});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSelectedActionPerformed
        // TODO add your handling code here:
        selectedRow = tblUniversity.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }else{
            DefaultTableModel tableModel = (DefaultTableModel) tblUniversity.getModel();
            University uni = (University) tableModel.getValueAt(selectedRow, 0);
            displayUniversity(uni);
            selectedUni = uni;
            btnAdvisor.setEnabled(true);
            btnExamCell.setEnabled(true);
        }
    }//GEN-LAST:event_btnViewSelectedActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        selectedRow = tblUniversity.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }else{
            DefaultTableModel tableModel = (DefaultTableModel) tblUniversity.getModel();
            University uni = (University) tableModel.getValueAt(selectedRow, 0);
            deleteUniversity(uni);
            selectedUni = uni;
            universities.clearAll();
            uniColleges.clearAll();
            uniDepartments.clearAll();
            advisors.clearAll();
            examCell.clearAll();
            getAllUniversityData();
            selectedCollegeId = 1;
            getAllExamCells();
            getAllAdvisors();
            clearAllFields();
            populateCompaniesTable(universities);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        clearAllFields();
        btnSave.setEnabled(true);
        txtDepartmentName.setEnabled(true);
        btnExamCell.setEnabled(false);
        btnAdvisor.setEnabled(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        if(res == 0) {
            ChoiceJPanel choicePanel = new ChoiceJPanel(splitPane, conn);
            splitPane.setRightComponent(choicePanel);
        }
        else{
            //Pressed No
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearAllFields();
        btnAdvisor.setEnabled(false);
        btnExamCell.setEnabled(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTableActionPerformed
        // TODO add your handling code here:
        populateCompaniesTable(universities);
    }//GEN-LAST:event_btnRefreshTableActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Please select a field:"));
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("Name");
        model.addElement("Career Advisor");
        model.addElement("Exam Cell Manager");
        
        JComboBox comboBox = new JComboBox(model);
        panel.add(comboBox);

        int resultField = JOptionPane.showConfirmDialog(null, panel, "Search by Field", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(resultField == JOptionPane.OK_OPTION){
            String fieldSelected = comboBox.getSelectedItem().toString();


            
            JTextField txtFieldName = new JTextField("");
            JTextField txtFieldAdv = new JTextField("");
            JTextField txtFieldExam = new JTextField("");
            
            panel.add(new JLabel("Value:"));
            
            if(fieldSelected.equalsIgnoreCase("Name")){
                comboBox.setEnabled(false);
                panel.add(txtFieldName);
            }else if(fieldSelected.equalsIgnoreCase("Location")){
                comboBox.setEnabled(false);
                panel.add(txtFieldAdv);
            }else{
                comboBox.setEnabled(false);
                panel.add(txtFieldExam);
            }

            int resultValue = JOptionPane.showConfirmDialog(null, panel, "Search by Field", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(resultValue == JOptionPane.OK_OPTION) {

                String fieldValue=null;
                if(fieldSelected.equalsIgnoreCase("Name")){
                    fieldValue = txtFieldName.getText();
                } else if(fieldSelected.equalsIgnoreCase("Location")){
                    fieldValue = txtFieldAdv.getText();
                } else{
                    fieldValue = txtFieldExam.getText();
                }

                if(fieldValue.equalsIgnoreCase("")){
                    JOptionPane.showMessageDialog(this, "Please enter a value");
                }else if(fieldSelected.equalsIgnoreCase("Name") && !isNameValid(fieldValue)){
                    JOptionPane.showMessageDialog(this, "Please enter a valid Name");
                }else if(fieldSelected.equalsIgnoreCase("Exam Cell Manager") && !isNameValid(fieldValue)){
                    JOptionPane.showMessageDialog(this, "Please enter a valid Name");
                }else if(fieldSelected.equalsIgnoreCase("Career Advisor") && !isNameValid(fieldValue)){
                    JOptionPane.showMessageDialog(this, "Please enter a valid Name");
                }else{
                    UniversityDir resultUniDir = new UniversityDir();
                    ArrayList<University> resultUnis = new ArrayList<University>();
                    
                    if(fieldSelected.equalsIgnoreCase("Name")){
                        resultUnis = universities.searchByNameMany(fieldValue);
                    }else if(fieldSelected.equalsIgnoreCase("Career Advisor")){
                        resultUnis.add(universities.searchById(advisors.searchByName(fieldValue).getUniversityId()));
                    }else{
                        resultUnis.add(universities.searchById(examCell.searchByName(fieldValue).getUniversityId()));
                    }

                    if(resultUnis.isEmpty()){
                        JOptionPane.showMessageDialog(this, "No Results Found");
                        populateCompaniesTable(universities);
                    }else{
                        JOptionPane.showMessageDialog(this, "Entries found");
                        
                        resultUniDir.setUniversityList(resultUnis);
                        populateCompaniesTable(resultUniDir);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "Search Cancelled");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Search Cancelled");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) tblUniversity.getModel();
        University uni = (University) tableModel.getValueAt(selectedRow, 0);
        updateUniversity(uni);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        saveStudentDetails();
        populateCompaniesTable(universities);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtUsernameExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameExamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameExamActionPerformed

    private void txtAdvisorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdvisorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdvisorNameActionPerformed

    private void txtDepartmentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartmentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartmentNameActionPerformed

    private void txtUsernameAdvisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameAdvisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameAdvisorActionPerformed

    private void btnExamCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamCellActionPerformed
        // TODO add your handling code here:
        UniExamCellJPanel examCellPanel = new UniExamCellJPanel(splitPane, conn, examCell.searchByUniversityId(selectedUni.getId()));
        splitPane.setRightComponent(examCellPanel);
    }//GEN-LAST:event_btnExamCellActionPerformed

    private void btnAdvisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvisorActionPerformed
        // TODO add your handling code here:
        UniCareerAdvisorJPanel advisorPanel = new UniCareerAdvisorJPanel(splitPane, conn, advisors.searchByUniversityId(selectedUni.getId()));
        splitPane.setRightComponent(advisorPanel);
    }//GEN-LAST:event_btnAdvisorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button btnAdd;
    private javax.swing.JButton btnAdvisor;
    private button.Button btnClear;
    private button.Button btnDelete;
    private javax.swing.JButton btnExamCell;
    private button.Button btnLogOut;
    private button.Button btnRefreshTable;
    private javax.swing.JButton btnSave;
    private button.Button btnSearch;
    private javax.swing.JButton btnUpdate;
    private button.Button btnViewSelected;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblHeading1;
    private javax.swing.JLabel lblHeading2;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentName1;
    private javax.swing.JTable tblUniversity;
    private javax.swing.JTextField txtAdvisorName;
    private javax.swing.JTextField txtDepartmentName;
    private javax.swing.JTextField txtExamCellName;
    private javax.swing.JTextField txtPasswordAdvisor;
    private javax.swing.JTextField txtPasswordExam;
    private javax.swing.JTextField txtUniversityName;
    private javax.swing.JTextField txtUsernameAdvisor;
    private javax.swing.JTextField txtUsernameExam;
    // End of variables declaration//GEN-END:variables

    public void getAllUniversityData(){
         try {
                //Universities
                String queryUniversity = "SELECT * FROM university";
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(queryUniversity);                
                while (rs.next())
                {
                    University university = universities.addUniversity();
                    
                    university.setId(rs.getInt("id"));
                    university.setName(rs.getString("name"));
                    university.setDistrict(rs.getString("district"));
                    university.setState(rs.getString("state"));
                    university.setCountry(rs.getString("country"));
                    university.setPincode(rs.getLong("pincode"));
                    university.setVisible(rs.getBoolean("visible"));
                }
                st.close();

                //Colleges
                String queryCollege = "SELECT * FROM uni_college";
                Statement stCollege = conn.createStatement();
                ResultSet rsCollege = stCollege.executeQuery(queryCollege);                
                while (rsCollege.next())
                {
                    UniCollege college = uniColleges.addUniCollege();
                    college.setId(rsCollege.getInt("id"));
                    college.setName(rsCollege.getString("name"));

                    for(University uni : universities.getUniversityList()){
                        if(uni.getId() == rsCollege.getInt("university_id")){
                            college.setUniversity(uni);
                        }
                    }

                }
                stCollege.close();

                //Departments
                Statement stDepartment = conn.createStatement();
                for(UniCollege college:uniColleges.getUniCollegeList()){
                    String queryDepartment = "SELECT * FROM uni_department WHERE uni_college_id = '" + college.getId() + "'";

                    ResultSet rsDepartment = stDepartment.executeQuery(queryDepartment);                
                    while (rsDepartment.next())
                    {
                        UniDepartment dept = uniDepartments.addUniDepartment();
                        dept.setId(rsDepartment.getInt("id"));
                        dept.setName(rsDepartment.getString("name"));
                        dept.setCollege(college);
    //                    for(UniCollege college : uniColleges.getUniCollegeList()){
    //                        if(college.getId() == rsDepartment.getInt("uni_college_id")){
    //                            dept.setCollege(college);
    //                        }
                    }
                
                }
                stDepartment.close();
              
                

            } catch (SQLException ex) {
                System.out.println("An error occurred. Maybe user/password is invalid");
                ex.printStackTrace();
        }       
    }
    
    public void clearAllFields(){
        txtUniversityName.setText("");
        txtDepartmentName.setText("");
        
        txtExamCellName.setText("");
        txtPasswordExam.setText("");
        txtUsernameExam.setText("");
        
        txtAdvisorName.setText("");
        txtPasswordAdvisor.setText("");
        txtUsernameAdvisor.setText("");
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(false);
        txtDepartmentName.setEnabled(false);
    }
    
    public void populateCmbBoxDepartments(Integer selectedCollegeId){
        
        DefaultComboBoxModel depts = new DefaultComboBoxModel();
        for(UniDepartment dept : uniDepartments.getUniDepartmentList()){
//            if(dept.getCollege().getId() == selectedCollegeId){
                depts.addElement(dept.getName());
//            }
        }

        

       
        
    }
    
    public void populateCmbBoxIntake(){
        LocalDate today = LocalDate.now();
        Integer year = today.getYear();
        ArrayList<Integer> listYears = new ArrayList<Integer>();
        for(int i=year - 2; i< year +  1; i++){
            listYears.add(i);
        }

        ArrayList<String> terms = new ArrayList<String>();
        terms.add("Spring");
        terms.add("Summer");
        terms.add("Fall");

        ArrayList<String> termsYears = new ArrayList<String>();
        for(Integer i : listYears){
            for(String j: terms){
                termsYears.add(j + " " + String.valueOf(i));
            }
        }

        DefaultComboBoxModel modelTermYear = new DefaultComboBoxModel();
        for(String str : termsYears){
            modelTermYear.addElement(str);
        }

        
    }
    
    public boolean isNameValid(String str) {
        String regex = "^[a-zA-Z0-9 ]{0,30}$";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher matcher = pattern.matcher(str);
        return matcher.matches();
    }
    
    public static boolean isUsernameValid(String str) { 
        String regex = "^[a-zA-Z0-9._]{0,100}$";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher matcher = pattern.matcher(str);
        return matcher.matches();
    }
    
    
    public static boolean isEmailValid(String str){
        String regex = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{1,})$";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher matcher = pattern.matcher(str);
        return matcher.matches();
    }
    
    public static boolean isCellNumberValid(String str){
        String regex = "^\\d{10}$";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher matcher = pattern.matcher(str);
        return matcher.matches();
    }
    
    public static boolean isSevisIdValid(String str){
        String regex = "[A-Z]+\\d{9}$";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher matcher = pattern.matcher(str);
        return matcher.matches();
    }
    
     public boolean isSevisIdUnique(String str){
        Boolean valid = true;
        for(UniStudent student : uniStudents.getUniStudentList()){
            if(student.getSevisId().equalsIgnoreCase(str)){
                valid = false;
            }
        }
        return valid;
    }
    
    public boolean isCourseNameValid(String str) {
        String regex = "^[a-zA-Z0-9 ]{0,100}$";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher matcher = pattern.matcher(str);
        return matcher.matches();
    }
    
    public void saveStudentDetails(){
        if( txtUniversityName.getText().equalsIgnoreCase("") || txtUsernameExam.getText().equalsIgnoreCase("") || 
                txtPasswordExam.getText().equalsIgnoreCase("") ||  txtUsernameAdvisor.getText().equalsIgnoreCase("") || 
                txtPasswordAdvisor.getText().equalsIgnoreCase("") || txtDepartmentName.getText().equalsIgnoreCase("") ||
                txtAdvisorName.getText().equalsIgnoreCase("") || txtExamCellName.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please fill all fields");
        }else{
            if(!isNameValid(txtUniversityName.getText())){
                JOptionPane.showMessageDialog(this, "Please enter a valid Name");
            }else if(!isNameUnique(txtUniversityName.getText())){
                JOptionPane.showMessageDialog(this, "University already exists. Please enter a valid Name");
            }else if(!isUsernameValid(txtUsernameAdvisor.getText())){
                JOptionPane.showMessageDialog(this, "Please ensure your Advisor Username only contains \nletters, numbers and symbols from . or _");
            }else if(!isUsernameValid(txtUsernameExam.getText())){
                JOptionPane.showMessageDialog(this, "Please ensure your Exam Cell Username only contains \nletters, numbers and symbols from . or _");
            }else if(!isUsernameUniqueAdvisor(txtUsernameAdvisor.getText())){
                JOptionPane.showMessageDialog(this, "Advisor username already exists. Please enter another username.");
            }else if(!isUsernameUniqueExamCell(txtUsernameExam.getText())){
                JOptionPane.showMessageDialog(this, "Exam Cell username already exists. Please enter another username.");
            }else if(!isNameValid(txtPasswordExam.getText())){
                JOptionPane.showMessageDialog(this, "Exam Cell password invalid. Please use only numbers and alphabets.");
            }else if(!isNameValid(txtPasswordAdvisor.getText())){
                JOptionPane.showMessageDialog(this, "Advisor password invalid. Please use only numbers and alphabets.");
            }else{
                saveUniversityDetails();
                
                clearAllFields();
                populateStudentTable(uniStudents);
                
            }
        }   
    }
    
    public void saveUniDetails(){
        {
//            query
//            clear
//            repopulate
        }
    }
    
    public void sendEmail(UniStudent recepient){
        
        Properties properties = new Properties();
        
        properties.put("mail.smtp.auth","true");
        properties.put("mail.smtp.starttls.enable","true");
        properties.put("mail.smtp.host","smtp.gmail.com");
        properties.put("mail.smtp.port","587");
        
        String myAccountEmail = "nice.job.app@gmail.com";
        String password = "pfwuxjdssssnikpi";
        
        Session session = Session.getInstance(properties, new Authenticator(){
            @Override
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(myAccountEmail,password);
            }
        });
        
        Message message = prepareMessage(session, myAccountEmail, recepient);
        try {
            Transport.send(message);
        } catch (MessagingException ex) {
            Logger.getLogger(SystemAdminUniversityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Message sent successfully");
   
    }
    
    private static Message prepareMessage(Session session, String myAccountEmail, UniStudent recepient){
        try {
            
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(myAccountEmail));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(recepient.getEmailId()));
            message.setSubject("Successful Account Registration");
            String msg = "<b>Hey "+ recepient.getName()+"!,</b> <br> <br>Your registration is complete. <br> <br>Below are your "
                    + "credentials: <br><b>Username:</b> "+recepient.getSevisId()+"<br><b>Password:</b> "+recepient.getPassword()+"<br> <br>You will not be granted access to Job Application Portal until your Advisor approves you.<br> <br>Regards,<br>Nice Job Team";
            message.setContent(msg, "text/html; charset=utf-8");
            return message;

        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(SystemAdminUniversityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public void getAllStudents(){
        try {
            String queryStudents = "SELECT * FROM uni_student WHERE university_id='"+selectedUniExamCell.getUniversityId()+"'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(queryStudents);                
                while (rs.next())
                {
                    UniStudent student = uniStudents.addUniStudent();
                    
                    student.setName(rs.getString("name"));
                    student.setSevisId(rs.getString("student_gov_id"));
                    student.setContactNo(rs.getLong("contact_no"));
                    student.setEmailId(rs.getString("email"));
                    student.setGpa(rs.getDouble("gpa"));
                    student.setIntake(rs.getString("intake"));
                    student.setSemester(rs.getInt("semester"));
                    student.setCourse(rs.getString("course"));
                    
                    UniDepartment department = uniDepartments.searchById(rs.getInt("uni_department_id"));
                    student.setDepartment(department);
                }
                st.close();
        } catch (SQLException ex) {
            Logger.getLogger(SystemAdminUniversityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void populateStudentTable(UniStudentDir uniStudents){
        DefaultTableModel tableModel = (DefaultTableModel) tblUniversity.getModel();
        tableModel.setRowCount(0);
        
        for(UniStudent student : uniStudents.getUniStudentList()){
            Object row[] = new Object[8];
            row[0] = student;
            row[1] = student.getName();
            row[2] = student.getContactNo().toString();
            row[3] = student.getEmailId();
            row[4] = student.getIntake();
            row[5] = student.getCourse();
            row[6] = student.getGpa();
            row[7] = student.getSemester().toString();
            
            tableModel.addRow(row);
        }
    }
    
    public void saveStudentToDb(UniStudent student){
        try {
            String queryNewStudent = "INSERT into uni_student (student_gov_id, name, contact_no, email, intake, course, gpa, semester, uni_department_id, work_eligibility, jd_watch_eligible, password, university_id) VALUES "
                    + "('" + student.getSevisId().toString() + "', '" + student.getName() + "' , '" + student.getContactNo().toString() + "' "
                    + ", '" + student.getEmailId() + "' , '" + student.getIntake() + "' , '" + student.getCourse() + "' , '" + student.getGpa().toString() + "' "
                    + ", '" + student.getSemester().toString() + "' , '" + student.getDepartment().getId().toString() + "' , '0' , '0' , '" + student.getPassword() + "',+ '"+student.getDepartment().getCollege().getUniversity().getId().toString()+"' )";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent); 
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(SystemAdminUniversityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static String generateRandomPassword(int len)
    {
        // ASCII range – alphanumeric (0-9, a-z, A-Z)
        final String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
 
        SecureRandom random = new SecureRandom();
        StringBuilder sb = new StringBuilder();
 
        // each iteration of the loop randomly chooses a character from the given
        // ASCII range and appends it to the `StringBuilder` instance
 
        for (int i = 0; i < len; i++)
        {
            int randomIndex = random.nextInt(chars.length());
            sb.append(chars.charAt(randomIndex));
        }
 
        return sb.toString();
    }
    
    public void displayStudent(UniStudent student){
        txtUniversityName.setText(student.getName());
        
        txtPasswordExam.setText(student.getContactNo().toString());
        txtUsernameExam.setText(student.getSevisId());
        
        
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        txtUsernameExam.setEnabled(false);
    }
    
    public void updateStudent(UniStudent oldStudent){
        if( txtUniversityName.getText().equalsIgnoreCase("") || txtUsernameExam.getText().equalsIgnoreCase("") || 
                txtPasswordExam.getText().equalsIgnoreCase("") 
                ){
            JOptionPane.showMessageDialog(this, "Please fill all fields");
        }else{
            if(!isNameValid(txtUniversityName.getText())){
                JOptionPane.showMessageDialog(this, "Please enter a valid Name");
            }else if(!isSevisIdValid(txtUsernameExam.getText())){
                JOptionPane.showMessageDialog(this, "Please enter a valid Sevid Id of form ABC123456789");
            }else if(!isCellNumberValid(txtPasswordExam.getText())){
                JOptionPane.showMessageDialog(this, "Please enter a valid Contact Number");
            }else{
                UniStudent student = new UniStudent();
                student.setName(txtUniversityName.getText());
                student.setSevisId(txtUsernameExam.getText());
                student.setContactNo(Long.valueOf(txtPasswordExam.getText()));
                
            
                student.setPassword(generateRandomPassword(8));
                
               

                
                uniStudents.updateUniStudent(oldStudent, student);
                             
                updateStudentToDb(oldStudent, student);
                clearAllFields();
                populateStudentTable(uniStudents);
                
            }
        }
    }
    
    public void updateStudentToDb(UniStudent oldStudent, UniStudent student){
        try {
            String queryNewStudent = "UPDATE uni_student SET name = '" + student.getName() + "' , contact_no = '" + student.getContactNo().toString() + "'"
                    + ", email = '" + student.getEmailId() + "', intake = '" + student.getIntake() + "', course = '" + student.getCourse() + "'"
                    + ", gpa = '" + student.getGpa().toString() + "', semester = '" + student.getSemester().toString() + "', uni_department_id = '" + student.getDepartment().getId().toString() + "' WHERE "
                    + "student_gov_id = '" + oldStudent.getSevisId() + "'";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent);   
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(SystemAdminUniversityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void deleteStudent(UniStudent student){
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this entry?", "Confirm Deletion", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.OK_OPTION ){
            uniStudents.deleteUniStudent(student);
            deleteStudentFromDb(student);
            clearAllFields();
            populateStudentTable(uniStudents);
        }else{
            JOptionPane.showMessageDialog(this, "Deletion cancelled");
        }
        
    }
    
    public void deleteStudentFromDb(UniStudent student){
        try {
            String queryNewStudent = "DELETE FROM uni_student WHERE "
                    + "student_gov_id = '" + student.getSevisId() + "'";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent);   
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(SystemAdminUniversityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void populateCompaniesTable(UniversityDir uniDir){
        DefaultTableModel tableModel = (DefaultTableModel) tblUniversity.getModel();
        tableModel.setRowCount(0);
        
        for(University uni : uniDir.getUniversityList()){
            if(uni.getVisible()){
                Object row[] = new Object[4];
            
                row[0] = uni;
                row[1] = uni.getName();
                row[2] = advisors.searchByUniversityId(uni.getId()).getName();
                row[3] = examCell.searchByUniversityId(uni.getId()).getName();


                tableModel.addRow(row);
            }
            
        }
    }
    
    public void getAllAdvisors(){
        try {
            String queryAdvisors = "SELECT * FROM uni_career_advisor";
            Statement stAdv = conn.createStatement();
            ResultSet rs = stAdv.executeQuery(queryAdvisors);                
                while (rs.next())
                {
                    UniCareerAdvisor advisor = advisors.addUniCareerAdvisor();
//                    UniDepartment filteredDept = uniDepartments.searchByAdvisorId(rs.getInt("id"));
//                    advisor.setDepartment(filteredDept);
                    advisor.setId(rs.getInt("id"));
                    advisor.setName(rs.getString("name"));
                    advisor.setPassword(rs.getString("password"));
                    advisor.setUsername(rs.getString("username"));
                    advisor.setUniversityId(rs.getInt("university_id"));
                }
                stAdv.close();
        } catch (SQLException ex) {
            Logger.getLogger(UniExamCellJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getAllExamCells(){
        try {
            String queryExamCells = "SELECT * FROM uni_exam_center";
            Statement stExamcell = conn.createStatement();
            ResultSet rs = stExamcell.executeQuery(queryExamCells);                
                while (rs.next())
                {
                    UniExamCell uniExamCellNew = examCell.addUniExamCell();
                    uniExamCellNew.setEmail(rs.getString("email"));
                    uniExamCellNew.setId(rs.getInt("id"));
                    uniExamCellNew.setName(rs.getString("name"));
                    uniExamCellNew.setPassword(rs.getString("password"));
                    uniExamCellNew.setUsername(rs.getString("username"));
                    uniExamCellNew.setUniversityId(rs.getInt("university_id"));
                    
                }
                stExamcell.close();
        } catch (SQLException ex) {
            Logger.getLogger(UniExamCellJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void displayUniversity(University uni){
        txtUniversityName.setText(uni.getName());
        ArrayList<UniDepartment> depts = uniDepartments.searchByIdArray(uni.getId());
        
        String deptString = "";
        for(UniDepartment dep : depts){
            if(deptString.equalsIgnoreCase("")){
                deptString = deptString + dep.getName();
            }else{
                deptString = deptString + "," + dep.getName();
            }
        }
        
        txtDepartmentName.setText(deptString);
        txtAdvisorName.setText(advisors.searchByUniversityId(uni.getId()).getName());
        txtUsernameAdvisor.setText(advisors.searchByUniversityId(uni.getId()).getUsername());
        txtPasswordAdvisor.setText(advisors.searchByUniversityId(uni.getId()).getPassword());
        txtExamCellName.setText(examCell.searchByUniversityId(uni.getId()).getName());
        txtUsernameExam.setText(examCell.searchByUniversityId(uni.getId()).getUsername());
        txtPasswordExam.setText(examCell.searchByUniversityId(uni.getId()).getPassword());
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }
    
    public boolean isUsernameUniqueAdvisor(String str) { 
        for(UniCareerAdvisor adv : advisors.getUniCareerAdvisorList()){
            if(adv.getUsername().equalsIgnoreCase(str)){
                return false;
            }
        }
        return true;
    }
    
    public boolean isUsernameUniqueExamCell(String str) { 
        for(UniExamCell ec : examCell.getUniExamCells()){
            if(ec.getUsername().equalsIgnoreCase(str)){
                return false;
            }
        }
        return true;
    }
    
    public boolean isNameUnique(String str) { 
        for(University uni : universities.getUniversityList()){
            if(uni.getName().equalsIgnoreCase(str)){
                return false;
            }
        }
        return true;
    }
    
    public void updateUniversity(University uni){
        updateUniversityDetails(uni);
        updateUniversityDetailsJobs(uni);
        updateAdvisorDetails(uni);
        updateExamCellDetails(uni);
        universities.clearAll();
        uniColleges.clearAll();
        uniDepartments.clearAll();
        advisors.clearAll();
        examCell.clearAll();
        getAllUniversityData();
        selectedCollegeId = 1;
        getAllExamCells();
        getAllAdvisors();
        clearAllFields();
        populateCompaniesTable(universities);
//      
    }
    
    public void updateUniversityDetails(University uni){
        try {
            String queryNewStudent = "UPDATE university SET name = '"+ txtUniversityName.getText() +"' WHERE id = '"+ uni.getId().toString() +"'";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent);   
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(SystemAdminUniversityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void updateUniversityDetailsJobs(University uni){
        try {
            String queryNewStudent = "UPDATE accepted_jobs SET university = '"+ txtUniversityName.getText() +"' WHERE university = '"+ uni.getName() +"'";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent);   
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(SystemAdminUniversityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void updateAdvisorDetails(University uni){
        try {
            String queryNewStudent = "UPDATE uni_career_advisor SET name = '"+ txtAdvisorName.getText() +"', username = '"+txtUsernameAdvisor.getText()+"', password = '"+txtPasswordAdvisor.getText()+"' WHERE university_id = '"+ uni.getId().toString() +"'";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent);   
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(SystemAdminUniversityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void updateExamCellDetails(University uni){
        try {
            String queryNewStudent = "UPDATE uni_exam_center SET name = '"+ txtExamCellName.getText() +"', username = '"+txtUsernameExam.getText()+"', password = '"+txtPasswordExam.getText()+"' WHERE university_id = '"+ uni.getId().toString() +"'";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent);   
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(SystemAdminUniversityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void deleteUniversity(University uni){
        try {
            String queryNewStudent = "UPDATE university SET visible = '0' WHERE id = '"+ uni.getId().toString() +"'";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent);   
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(SystemAdminUniversityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void saveUniversityDetails(){
        saveUniversityDetailsDb();
        universities.clearAll();
        uniColleges.clearAll();
        uniDepartments.clearAll();
        advisors.clearAll();
        examCell.clearAll();
        getAllUniversityData();
        selectedCollegeId = 1;
        getAllExamCells();
        getAllAdvisors();
//        
        String uniId = universities.searchByName(txtUniversityName.getText()).getId().toString();
        saveCollegeDetailsDb(uniId);
        saveAdvisorDetailsDb(uniId);
        saveExamCellDetailsDb(uniId);
        
        universities.clearAll();
        uniColleges.clearAll();
        uniDepartments.clearAll();
        advisors.clearAll();
        examCell.clearAll();
        getAllUniversityData();
        selectedCollegeId = 1;
        getAllExamCells();
        getAllAdvisors();
        
        String collegeId = uniColleges.searchByUniversity(universities.searchByName(txtUniversityName.getText())).getId().toString();
        String[] depts = txtDepartmentName.getText().split(",");
        for (String st : depts){
            saveDeptDetailsDb(collegeId, st);
        }
//        saveDeptsDb();

        universities.clearAll();
        uniColleges.clearAll();
        uniDepartments.clearAll();
        advisors.clearAll();
        examCell.clearAll();
        getAllUniversityData();
        selectedCollegeId = 1;
        getAllExamCells();
        getAllAdvisors();
        populateCompaniesTable(universities);
    }
    
    public void saveUniversityDetailsDb(){
        try {
            String queryNewStudent = "INSERT into university (name, district, state, country, pincode, visible) VALUES "
                    + "('" + txtUniversityName.getText() + "', 'Mumbai', 'Maharashtra', 'India', '400080', '1')";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent); 
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(UniExamCellJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void saveCollegeDetailsDb(String id){
        try {
            String queryNewStudent = "INSERT into uni_college(name, university_id) VALUES "
                    + "('Mumbai', '"+id+"')";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent); 
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(UniExamCellJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void saveAdvisorDetailsDb(String id){
        try {
            String queryNewStudent = "INSERT into uni_career_advisor(name, university_id, username, password, uni_department_id) VALUES "
                    + "('"+txtAdvisorName.getText()+"', '"+id+"' , '"+txtUsernameAdvisor.getText()+"' , '"+txtPasswordAdvisor.getText()+"' , '1')";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent); 
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(UniExamCellJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void saveExamCellDetailsDb(String id){
        try {
            String queryNewStudent = "INSERT into uni_exam_center(name, university_id, username, password, email) VALUES "
                    + "('"+txtExamCellName.getText()+"', '"+id+"' , '"+txtUsernameExam.getText()+"' , '"+txtPasswordExam.getText()+"' , '1')";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent); 
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(UniExamCellJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void saveDeptDetailsDb(String id, String name){
        try {
            String queryNewStudent = "INSERT into uni_department(name, uni_college_id, uni_advisor_id) VALUES "
                    + "('"+name+"', '"+id+"' , '1')";
            Statement st = conn.createStatement();
            st.executeUpdate(queryNewStudent); 
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(UniExamCellJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
